export const periodicTable = [
    [
        { name: 'Hydrogen', symbol: 'H', number: 1, weight: 1.008 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: 'Helium', symbol: 'He', number: 2, weight: 4.0026 },
    ],
    [
        { name: 'Lithium', symbol: 'Li', number: 3, weight: 6.941 },
        { name: 'Beryllium', symbol: 'Be', number: 4, weight: 9.012 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: 'Boron', symbol: 'B', number: 5, weight: 10.811 },
        { name: 'Carbon', symbol: 'C', number: 6, weight: 12.011 },
        { name: 'Nitrogen', symbol: 'N', number: 7, weight: 14.007 },
        { name: 'Oxygen', symbol: 'O', number: 8, weight: 15.999 },
        { name: 'Fluorine', symbol: 'F', number: 9, weight: 18.998 },
        { name: 'Neon', symbol: 'Ne', number: 10, weight: 20.18 },


    ],
    [
        { name: 'Sodium', symbol: 'Na', number: 11, weight: 22.9898 },
        { name: 'Magnesium', symbol: 'Mg', number: 12, weight: 24.305 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: 'Aluminum', symbol: 'Al', number: 13, weight: 26.982 },
        { name: 'Silicon', symbol: 'Si', number: 14, weight: 28.086 },
        { name: 'Phosphorus', symbol: 'P', number: 15, weight: 30.974 },
        { name: 'Sulfur', symbol: 'S', number: 16, weight: 32.065 },
        { name: 'Chlorine', symbol: 'Cl', number: 17, weight: 35.453 },
        { name: 'Argon', symbol: 'Ar', number: 18, weight: 39.948 },
    ],
    [
        { name: 'Potassium', symbol: 'K', number: 19, weight: 39.098 },
        { name: 'Calcium', symbol: 'Ca', number: 20, weight: 40.078 },
        { name: 'Scandium', symbol: 'Sc', number: 21, weight: 44.956 },
        { name: 'Titanium', symbol: 'Ti', number: 22, weight: 47.867 },
        { name: 'Vanadium', symbol: 'V', number: 23, weight: 50.942 },
        { name: 'Chromium', symbol: 'Cr', number: 24, weight: 51.996, icon: 'chromium-browser' },
        { name: 'Manganese', symbol: 'Mn', number: 25, weight: 54.938 },
        { name: 'Iron', symbol: 'Fe', number: 26, weight: 55.845 },
        { name: 'Cobalt', symbol: 'Co', number: 27, weight: 58.933 },
        { name: 'Nickel', symbol: 'Ni', number: 28, weight: 58.693 },
        { name: 'Copper', symbol: 'Cu', number: 29, weight: 63.546 },
        { name: 'Zinc', symbol: 'Zn', number: 30, weight: 65.38 },
        { name: 'Gallium', symbol: 'Ga', number: 31, weight: 69.723 },
        { name: 'Germanium', symbol: 'Ge', number: 32, weight: 72.630 },
        { name: 'Arsenic', symbol: 'As', number: 33, weight: 74.9216 },
        { name: 'Selenium', symbol: 'Se', number: 34, weight: 78.96 },
        { name: 'Bromine', symbol: 'Br', number: 35, weight: 79.904 },
        { name: 'Krypton', symbol: 'Kr', number: 36, weight: 83.798 },
    ],
    [
        { name: 'Rubidium', symbol: 'Rb', number: 37, weight: 85.4678 },
        { name: 'Strontium', symbol: 'Sr', number: 38, weight: 87.62 },
        { name: 'Yttrium', symbol: 'Y', number: 39, weight: 88.9059 },
        { name: 'Zirconium', symbol: 'Zr', number: 40, weight: 91.224 },
        { name: 'Niobium', symbol: 'Nb', number: 41, weight: 92.906 },
        { name: 'Molybdenum', symbol: 'Mo', number: 42, weight: 95.94 },
        { name: 'Technetium', symbol: 'Tc', number: 43, weight: 98 },
        { name: 'Ruthenium', symbol: 'Ru', number: 44, weight: 101.07 },
        { name: 'Rhodium', symbol: 'Rh', number: 45, weight: 102.91 },
        { name: 'Palladium', symbol: 'Pd', number: 46, weight: 106.42 },
        { name: 'Silver', symbol: 'Ag', number: 47, weight: 107.868 },
        { name: 'Cadmium', symbol: 'Cd', number: 48, weight: 112.411 },
        { name: 'Indium', symbol: 'In', number: 49, weight: 114.818 },
        { name: 'Tin', symbol: 'Sn', number: 50, weight: 118.71 },
        { name: 'Antimony', symbol: 'Sb', number: 51, weight: 121.76 },
        { name: 'Tellurium', symbol: 'Te', number: 52, weight: 127.6 },
        { name: 'Iodine', symbol: 'I', number: 53, weight: 126.9 },
        { name: 'Xenon', symbol: 'Xe', number: 54, weight: 131.29 },
    ],
    [
        { name: 'Cesium', symbol: 'Cs', number: 55, weight: 132.905 },
        { name: 'Barium', symbol: 'Ba', number: 56, weight: 137.327 },
        { name: 'Lanthanum', symbol: 'La', number: 57, weight: 138.906 },
        { name: 'Hafnium', symbol: 'Hf', number: 72, weight: 178.49 },
        { name: 'Tantalum', symbol: 'Ta', number: 73, weight: 180.948 },
        { name: 'Tungsten', symbol: 'W', number: 74, weight: 183.84 },
        { name: 'Rhenium', symbol: 'Re', number: 75, weight: 186.207 },
        { name: 'Osmium', symbol: 'Os', number: 76, weight: 190.23 },
        { name: 'Iridium', symbol: 'Ir', number: 77, weight: 192.217 },
        { name: 'Platinum', symbol: 'Pt', number: 78, weight: 195.085 },
        { name: 'Gold', symbol: 'Au', number: 79, weight: 196.967 },
        { name: 'Mercury', symbol: 'Hg', number: 80, weight: 200.59 },
        { name: 'Thallium', symbol: 'Tl', number: 81, weight: 204.383 },
        { name: 'Lead', symbol: 'Pb', number: 82, weight: 207.2 },
        { name: 'Bismuth', symbol: 'Bi', number: 83, weight: 208.980 },
        { name: 'Polonium', symbol: 'Po', number: 84, weight: 209 },
        { name: 'Astatine', symbol: 'At', number: 85, weight: 210 },
        { name: 'Radon', symbol: 'Rn', number: 86, weight: 222 },
    ],
    [
        { name: 'Francium', symbol: 'Fr', number: 87, weight: 223 },
        { name: 'Radium', symbol: 'Ra', number: 88, weight: 226 },
        { name: 'Actinium', symbol: 'Ac', number: 89, weight: 227 },
        { name: 'Rutherfordium', symbol: 'Rf', number: 104, weight: 267 },
        { name: 'Dubnium', symbol: 'Db', number: 105, weight: 268 },
        { name: 'Seaborgium', symbol: 'Sg', number: 106, weight: 271 },
        { name: 'Bohrium', symbol: 'Bh', number: 107, weight: 272 },
        { name: 'Hassium', symbol: 'Hs', number: 108, weight: 277 },
        { name: 'Meitnerium', symbol: 'Mt', number: 109, weight: 278 },
        { name: 'Darmstadtium', symbol: 'Ds', number: 110, weight: 281 },
        { name: 'Roentgenium', symbol: 'Rg', number: 111, weight: 280 },
        { name: 'Copernicium', symbol: 'Cn', number: 112, weight: 285 },
        { name: 'Nihonium', symbol: 'Nh', number: 113, weight: 286 },
        { name: 'Flerovium', symbol: 'Fl', number: 114, weight: 289 },
        { name: 'Moscovium', symbol: 'Mc', number: 115, weight: 290 },
        { name: 'Livermorium', symbol: 'Lv', number: 116, weight: 293 },
        { name: 'Tennessine', symbol: 'Ts', number: 117, weight: 294 },
        { name: 'Oganesson', symbol: 'Og', number: 118, weight: 294 },
    ],
]

export const series = [
    [
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: 'Cerium', symbol: 'Ce', number: 58, weight: 140.12 },
        { name: 'Praseodymium', symbol: 'Pr', number: 59, weight: 140.91 },
        { name: 'Neodymium', symbol: 'Nd', number: 60, weight: 144.24 },
        { name: 'Promethium', symbol: 'Pm', number: 61, weight: 145 },
        { name: 'Samarium', symbol: 'Sm', number: 62, weight: 150.36 },
        { name: 'Europium', symbol: 'Eu', number: 63, weight: 151.96 },
        { name: 'Gadolinium', symbol: 'Gd', number: 64, weight: 157.25 },
        { name: 'Terbium', symbol: 'Tb', number: 65, weight: 158.93 },
        { name: 'Dysprosium', symbol: 'Dy', number: 66, weight: 162.5 },
        { name: 'Holmium', symbol: 'Ho', number: 67, weight: 164.93 },
        { name: 'Erbium', symbol: 'Er', number: 68, weight: 167.26 },
        { name: 'Thulium', symbol: 'Tm', number: 69, weight: 168.93 },
        { name: 'Ytterbium', symbol: 'Yb', number: 70, weight: 173.04 },
        { name: 'Lutetium', symbol: 'Lu', number: 71, weight: 174.97 },
    ],
    [
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: '', symbol: '', number: -1, weight: 0 },
        { name: 'Thorium', symbol: 'Th', number: 90, weight: 232.04 },
        { name: 'Protactinium', symbol: 'Pa', number: 91, weight: 231.04 },
        { name: 'Uranium', symbol: 'U', number: 92, weight: 238.03 },
        { name: 'Neptunium', symbol: 'Np', number: 93, weight: 237 },
        { name: 'Plutonium', symbol: 'Pu', number: 94, weight: 244 },
        { name: 'Americium', symbol: 'Am', number: 95, weight: 243 },
        { name: 'Curium', symbol: 'Cm', number: 96, weight: 247 },
        { name: 'Berkelium', symbol: 'Bk', number: 97, weight: 247 },
        { name: 'Californium', symbol: 'Cf', number: 98, weight: 251 },
        { name: 'Einsteinium', symbol: 'Es', number: 99, weight: 252 },
        { name: 'Fermium', symbol: 'Fm', number: 100, weight: 257 },
        { name: 'Mendelevium', symbol: 'Md', number: 101, weight: 258 },
        { name: 'Nobelium', symbol: 'No', number: 102, weight: 259 },
        { name: 'Lawrencium', symbol: 'Lr', number: 103, weight: 262 },
    ],
]