[aux]
file=
ignore_non_chinese=true
in=
out=

[py]
custom=
ignore_non_chinese=true
in=
out=
skip=cuoyin.dict.yaml\nduoyin.dict.yaml\nrenming.dict.yaml\nzi.dict.yaml

[sp]
in=
in_sep=" "
is_jianma=false
out=
out_sep=" "
schema=0

[ui]
dark=false

[upd]
aux_index=0
clean=false
clean_build=false
custom_url=
rime=/home/ryou/.local/share/fcitx5/rime
scope=0
source_type=0
src_mode=1
token=
ver=0
whitelist=^custom_phrase\\.txt$\n.*userdb$\n.*\\.custom\\.yaml$\n^user\\.yaml$\n^installation\\.yaml$\n^sync/.*
