#!/usr/bin/env bash

cd "$HOME/.config/eww" || exit
filelist=$(ls 'images/svg/template/' | grep -v /)

colorscss=$(cat css/_material.scss)
echo "$colorscss" | grep 'onPrimaryContainer' | awk '{print $2}' | cut -d ";" -f1


IFS=$'\n'
filearr=($(echo "$filelist")) # Get colors

for i in "${!filearr[@]}"; do
    echo "images/svg/${filearr[$i]}"
    colorvalue=$(echo "$colorscss" | grep "${filearr[$i]}" | awk '{print $2}' | cut -d ";" -f1)
    
    for file in images/svg/template/"${filearr[$i]}"/*; do 
        cp "$file" images/svg/
        sed -i "s/black/$colorvalue/g" images/svg/"${file##*/}"
    done
    # sed -i "s/white/$1/gi" "images/svg/${filearr[$i]}"
done