#!/usr/bin/bash
getoptions(){
  gaps_in=$(hyprctl getoption general:gaps_in -j | gojq -r -c '.int')
  gaps_out=$(hyprctl getoption general:gaps_out -j | gojq -r -c '.int')
  border_size=$(hyprctl getoption general:border_size -j | gojq -r -c '.int')
  force_no_accel=$(hyprctl getoption input:force_no_accel -j | gojq -r -c '.int')
  input_sensitivity=$(hyprctl getoption input:sensitivity -j | gojq -r -c '.float')
  touchpad_disable_while_typing=$(hyprctl getoption input:touchpad:disable_while_typing -j | gojq -r -c '.int')
  touchpad_clickfinger_behavior=$(hyprctl getoption input:touchpad:clickfinger_behavior -j | gojq -r -c '.int')

  echo -n '{'
  echo -n "\"gaps_in\":$gaps_in,"
  echo -n "\"gaps_out\":$gaps_out,"
  echo -n "\"border_size\":$border_size,"
  echo -n "\"force_no_accel\":$force_no_accel,"
  echo -n "\"input_sensitivity\":$input_sensitivity,"
  echo -n "\"touchpad_disable_while_typing\":$touchpad_disable_while_typing,"
  echo -n "\"touchpad_clickfinger_behavior\":$touchpad_clickfinger_behavior,"

  echo '"dummy":0}'
}

getoptions

if [ "$1" == "--once" ]; then
  exit 0
else
  socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r line; do
    getoptions
  done
fi