#!/usr/bin/env bash

while true; do    
  # human-readable
  freeH=$(free -h --si | rg "Mem:")
  swapfreeH=$(free -h --si | rg "Swap:")
  # non-human-readable
  freeN=$(free --mega | rg "Mem:")
  swapfreeN=$(free --mega | rg "Swap:")

  total="$(echo "$freeH" | awk '{ print $2 }')"
  used="$(echo "$freeH" | awk '{ print $3 }')"
  t="$(echo "$freeN" | awk '{ print $2 }')"
  u="$(echo "$freeN" | awk '{ print $3 }')"

  swaptotal="$(echo "$swapfreeH" | awk '{ print $2 }')"
  swapused="$(echo "$swapfreeH" | awk '{ print $3 }')"
  swapt="$(echo "$swapfreeN" | awk '{ print $2 }')"
  swapu="$(echo "$swapfreeN" | awk '{ print $3 }')"

  free=0
  perc=0

  swapfree=0
  swappercentage=0

  total_mem=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
  available_mem=$(awk '/MemAvailable/ {print $2}' /proc/meminfo)

  used_mem=$((total_mem - available_mem))

  percentage=$((used_mem * 100 / total_mem))

  echo '{"total": "'"$total"'", "used": "'"$used"'", "swaptotal": "'"$swaptotal"'", "swapused": "'"$swapused"'", "swappercentage": "'"$swappercentage"'", "swapfree": "'"$swapfree"'", "percentage": "'"$percentage"'" }'

  sleep 3
done