#!/usr/bin/bash

scripts/taskbar

if [ "$1" == "--once" ]; then
  scripts/taskbar
  exit 0
else
  socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | rg --line-buffered "window>>" | while read -r line; do
    scripts/taskbar
    echo
  done
fi