#!/usr/bin/bash
getwinlist(){
  toprint=$(hyprctl clients -j \
    | grep -v '"xwayland": ' \
    | grep -v '"grouped": ' \
    | grep -v '"pid": ' \
    | grep -v '"fullscreenMode": ' \
    | grep -v '"monitor": ' \
    | grep -v '"floating": ' \
    | grep -v '"fullscreen": ' \
    | grep -v '"at": ' \
    | grep -v '"pinned":') # | grep -v ""name":")
  # echo '-=-=-=- final output -=-=-=-'
  # echo "$toprint"
  echo $(echo "$toprint")  # Print on one line only
}

getwinlist

if [ "$1" == "--once" ]; then
  exit 0
else
  socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | rg --line-buffered "window>>" | while read -r line; do
    # echo $line
    getwinlist
  done
fi