import qs.modules.common
import qs.modules.common.widgets
import qs.modules.common.functions
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtQuick.Effects

/**
Mostly generated by Grok
*/
Item {
    id: root

    property string buttonIcon: "star"
    property bool customIcon: false
    property bool halfToggled: false
    property bool toggled: false
    property string toggleText: "Toggle"
    property string stateText: toggled ? "On" : "Off"
    property int sizeType: 2 // 1: compact (icon-only), 2: expanded (icon + text)
    property var downAction // Triggered when clicking icon area
    property var altAction: downAction // Triggered when clicking text area . same if not specified
    property var middleClickAction // When middle clicking
    property real baseHeight: 65
    property real baseWidth: baseHeight * sizeType + (sizeType - 1) * gap
    property bool down: false
    property int gap: 16
    property bool isSupported: true

    Layout.fillWidth: true
    Layout.fillHeight: true
    implicitWidth: baseWidth
    implicitHeight: baseHeight

    property color colBackground: Appearance?.colors.colLayer3
    property color colBackgroundBorder: Appearance?.colors.colLayer4
    property color colBackgroundHover: Appearance?.colors.colLayer2
    property color colBackgroundActive: Appearance?.colors.colLayer1
    property color colBackgroundToggled: Appearance?.colors.colPrimary ?? "#65558F"
    property color colBackgroundToggledHover: Appearance?.colors.colPrimaryHover ?? "#77699C"
    property color colBackgroundToggledActive: Appearance?.colors.colPrimaryActive ?? "#D6CEE2"

    property real buttonRadiusPressed: Math.min(baseHeight, baseWidth) / 2.5
    property real buttonRadius: (altAction && toggled) ? buttonRadiusPressed : Math.min(baseHeight, baseWidth) / 2

    property real radius: root.down ? buttonRadiusPressed : buttonRadius
    property real leftRadius: root.down ? buttonRadiusPressed : buttonRadius
    property real rightRadius: root.down ? buttonRadiusPressed : buttonRadius

    // color change based on states
    property color color: root.toggled || root.halfToggled ? (root.down ? colBackgroundToggledActive : hoverHandler.hovered ? colBackgroundToggledHover : colBackgroundToggled) : (root.down ? colBackgroundActive : hoverHandler.hovered ? colBackgroundHover : colBackground)

    // color change for sizeType == 2 for background
    property color backgroundColor: (root.down ? colBackgroundActive : hoverHandler.hovered ? colBackgroundHover : colBackground)

    Behavior on leftRadius {
        animation: Appearance.animation.elementMoveFast.numberAnimation.createObject(this)
    }
    Behavior on rightRadius {
        animation: Appearance.animation.elementMoveFast.numberAnimation.createObject(this)
    }
    Behavior on color {
        animation: Appearance.animation.elementMoveFast.colorAnimation.createObject(this)
    }
    Behavior on backgroundColor {
        animation: Appearance.animation.elementMoveFast.colorAnimation.createObject(this)
    }
    Behavior on scale {
        animation: Appearance.animation.elementMove.numberAnimation.createObject(this)
    }

    HoverHandler {
        id: hoverHandler
        acceptedDevices: PointerDevice.Mouse | PointerDevice.TouchPad
        cursorShape: Qt.PointingHandCursor
    }

    Rectangle {
        id: buttonBackground
        anchors.fill: parent
        topLeftRadius: root.leftRadius
        topRightRadius: root.rightRadius
        bottomLeftRadius: root.leftRadius
        bottomRightRadius: root.rightRadius
        implicitHeight: 50

        // border.width: 1
        // border.color: colBackgroundBorder
        color: sizeType === 2 ? root.backgroundColor : root.color
        Behavior on color {
            animation: Appearance.animation.elementMoveFast.colorAnimation.createObject(this)
        }
    }

    RowLayout {
        anchors.fill: parent
        spacing: 0
        clip: true
        // Icon Area
        Rectangle {
            id: toggleIcon
            width: baseHeight - (sizeType - 1) * gap
            height: baseHeight - (sizeType - 1) * gap
            Layout.leftMargin: (sizeType - 1) * (gap / 2)
            Layout.rightMargin: Layout.leftMargin
            Layout.fillWidth: sizeType === 1 ? parent : null
            Layout.fillHeight: sizeType === 1 ? parent : null
            color: sizeType == 2 ? root.color : "transparent"
            radius: buttonRadius
            // border.width: 0
            // border.color: "red"

            Behavior on radius {
                animation: Appearance.animation.elementMoveFast.numberAnimation.createObject(this)
            }

            Behavior on color {
                animation: Appearance.animation.elementMoveFast.colorAnimation.createObject(this)
            }

            Loader {
                anchors.centerIn: toggleIcon
                sourceComponent: customIcon ? customIconComponent : materialSymbolComponent
            }

            MouseArea {
                anchors.fill: toggleIcon
                cursorShape: Qt.PointingHandCursor
                acceptedButtons: Qt.RightButton | Qt.LeftButton | Qt.MiddleButton
                hoverEnabled: true

                onPressed: event => {
                    if (event.button === Qt.MiddleButton) {
                        if (root.middleClickAction)
                            root.middleClickAction();
                    } else if (event.button === Qt.RightButton && sizeType === 1) {
                        if (root.altAction)
                            root.altAction();
                    } else {
                        root.down = true;
                        if (root.downAction)
                            root.downAction();
                    }
                    root.scale = 0.9;
                }

                onReleased: event => {
                    root.down = false;
                    root.scale = 1;
                }
            }
        }

        // Text Area (visible only when sizeType === 2)
        Rectangle {
            id: toggleInfo
            visible: sizeType === 2
            Layout.fillWidth: true
            Layout.fillHeight: true
            Layout.rightMargin: gap
            // border.width: 0
            // border.color: "black"
            color: "transparent"
            clip: true
            ColumnLayout {
                anchors.verticalCenter: parent.verticalCenter
                spacing: 0

                StyledLabel {
                    Layout.alignment: Qt.AlignVCenter
                    Layout.leftMargin: 10
                    text: toggleText
                    color: Appearance.colors.colOnLayer1
                    font {
                        pixelSize: Appearance.font.pixelSize.small
                        weight: Font.Medium
                    }
                }
                StyledLabel {
                    Layout.alignment: Qt.AlignVCenter
                    Layout.leftMargin: 10
                    Layout.topMargin: 2
                    visible: stateText !== ""
                    font {
                        pixelSize: Appearance.font.pixelSize.small
                        weight: Font.Normal
                    }
                    text: stateText
                    color: Appearance.colors.colOnLayer4
                    opacity: 0.6
                }
            }
            MouseArea {
                anchors.fill: parent
                cursorShape: Qt.PointingHandCursor
                acceptedButtons: Qt.LeftButton | Qt.RightButton
                onPressed: event => {
                    root.down = true;
                    if (root.altAction)
                        root.altAction();
                }
                onReleased: event => {
                    root.down = false;
                }
            }
        }
    }

    Component {
        id: materialSymbolComponent
        MaterialSymbol {
            anchors.centerIn: parent
            iconSize: 24
            fill: toggled ? 1 : 0
            color: toggled || halfToggled ? Appearance.m3colors.m3onPrimary : Appearance.colors.colOnLayer1
            horizontalAlignment: Text.AlignHCenter
            verticalAlignment: Text.AlignVCenter
            text: buttonIcon
            Behavior on color {
                animation: Appearance.animation.elementMoveFast.colorAnimation.createObject(this)
            }
        }
    }
    Component {
        id: customIconComponent
        CustomIcon {
            id: distroIcon
            source: buttonIcon
            anchors.centerIn: parent
            width: 24
            height: 24

            colorize: true
            color: root.toggled ? Appearance.m3colors.m3onPrimary : Appearance.colors.colOnLayer1

            Behavior on color {
                animation: Appearance.animation.elementMoveFast.colorAnimation.createObject(this)
            }
        }
    }
}
