# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = fcitx5
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gnome-keyring-daemon --start --components=secrets

env = XCURSOR_THEME,macOS
env = XCURSOR_SIZE,24

exec-once = hyprctl setcursor macOS 24

permission = fcitx5-vmk-server, keyboard, allow
