# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Alt-Tab / window switcher helper (see custom/keybinds.conf for binds)
exec-once = snappy-wrapper

# Workaround: Hyprland sometimes assigns the second monitor to the wrong workspace on boot
# exec-once = sleep 2 && hyprctl --batch "dispatch focusmonitor DP-2; dispatch workspace 6; dispatch focusmonitor DP-1; dispatch workspace 1"

# Input method
# exec-once = fcitx5
