# hyprlang noerror false
# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

windowrule = match:class .*, no_blur off

windowrule = opacity 0.9 override 0.9 override, match:class ^spotify$
windowrule = opacity 0.98 override 0.98 override, match:class ^google-chrome$
windowrule = opacity 0.9 override 0.9 override, match:class ^discord$
windowrule = opacity 0.75 override 0.75 override, match:class ^org\.kde\.dolphin$

# Quickshell panels
layerrule = ignore_alpha 0.85, match:namespace quickshell:.*
layerrule = xray off, match:namespace quickshell:.*
layerrule = blur on, match:namespace quickshell:.*

windowrule = float 1, match:class ^(pot)$
windowrule = pin 1, match:class ^(pot)$


permission = fcitx5-vmk-server, keyboard, allow
