pkgname=illogical-impulse-fonts-themes
pkgver=1.0
pkgrel=1
pkgdesc='Illogical Impulse Fonts and Theming Dependencies'
arch=(any)
license=(None)
depends=(
  adw-gtk-theme-git
  breeze
  breeze-plus
  darkly-bin
  eza
  fish
  fontconfig
  kde-material-you-colors
  kitty
  matugen-bin
  otf-space-grotesk
  starship
  ttf-gabarito-git
  ttf-jetbrains-mono-nerd
  ttf-material-symbols-variable-git
  ttf-readex-pro
  ttf-rubik-vf
  ttf-twemoji
)
