# Don't print a new line at the start of the prompt
add_newline = false

format = """
$cmd_duration$directory$git_branch$git_status$nodejs$python$rust$lua$direnv
$character"""

[character]
success_symbol = "[󰄾](bold green) "
error_symbol = "[󰄾](bold red) "
vimcmd_symbol = "[󰄾](bold blue) "

[directory]
style = "bold cyan"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"
read_only = " 󰌾"

[directory.substitutions]
"Desktop" = "󰇄"
"Documents" = "󰈙"
"Downloads" = "󰉍"
"Music" = "󰎈"
"Pictures" = "󰉏"
"Videos" = "󰈫"

[git_branch]
symbol = "󰊢 "
style = "bold magenta"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style)) "
conflicted = "󰞇 "
ahead = "󰶣 "
behind = "󰶡 "
diverged = "󰶤 "
untracked = "󰋗 "
stashed = "󰟬 "
modified = "󰷫 "
staged = "󰄬 "
renamed = "󰑍 "
deleted = "󰧧 "

[nodejs]
symbol = "󰎙 "
style = "bold green"
format = "via [$symbol($version )]($style)"

[python]
symbol = "󰌠 "
style = "bold yellow"
format = 'via [$symbol($version )(\($virtualenv\) )]($style)'

[rust]
symbol = "󱘗 "
style = "bold orange"
format = "via [$symbol($version )]($style)"

[lua]
symbol = "󰢱 "
style = "bold blue"
format = "via [$symbol($version )]($style)"

[cmd_duration]
min_time = 500
style = "bold yellow"
format = "took [$duration]($style) "

[package]
disabled = true

[hostname]
disabled = true

[username]
disabled = true
