#!/bin/sh


cp ~/.config/hypr/hyprland.conf temporary_config.conf && cp temporary_config.conf ~/.config/hypr/hyprland.conf
rm temporary_config.conf

pkill swaybg
swaybg -i images/wallpaper/wallpaper-normal

kill $(pidof eww) && eww open bar && eww open bg-decor
