
#!/usr/bin/env python3

import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
TRANSACTION_SCRIPT = SCRIPT_DIR / "display_transaction.py"

CONFIG_HOME = Path(
    os.environ.get(
        "XDG_CONFIG_HOME",
        str(Path.home() / ".config")
    )
)

MONITORS_FILE = CONFIG_HOME / "hypr" / "monitors.lua"
BACKUP_FILE = MONITORS_FILE.with_name(
    "monitors.lua.vesta-backup"
)

PERSIST_ACTIONS = {"confirm", "positions"}


def run_command(command, timeout=30):
    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
        timeout=timeout
    )

    if result.returncode != 0:
        raise RuntimeError(
            result.stderr.strip()
            or result.stdout.strip()
            or "Command failed"
        )

    return result.stdout.strip()


def read_monitors():
    data = json.loads(
        run_command(["hyprctl", "monitors", "-j"])
    )

    if not isinstance(data, list) or not data:
        raise RuntimeError(
            "No active monitors available for persistence"
        )

    return data


def monitor_mode(monitor):
    resolution = (
        f"{int(monitor['width'])}x"
        f"{int(monitor['height'])}"
    )

    refresh = float(monitor["refreshRate"])

    candidates = []

    for entry in monitor.get("availableModes", []):
        clean = str(entry).removesuffix("Hz")

        if not clean.startswith(resolution + "@"):
            continue

        try:
            frequency = float(clean.split("@", 1)[1])
        except ValueError:
            continue

        candidates.append((
            abs(frequency - refresh),
            clean
        ))

    if candidates:
        difference, mode = min(candidates)

        if difference < 0.5:
            return mode

    return f"{resolution}@{refresh:.5f}"


def lua_string(value):
    return json.dumps(str(value), ensure_ascii=True)


def finite_number(value, label):
    number = float(value)

    if not math.isfinite(number):
        raise ValueError(f"Invalid {label}")

    return number


def monitor_block(monitor):
    name = str(monitor["name"])
    mode = monitor_mode(monitor)

    x = int(round(finite_number(monitor["x"], "X position")))
    y = int(round(finite_number(monitor["y"], "Y position")))

    scale = finite_number(monitor["scale"], "scale")

    if scale <= 0:
        raise ValueError("Monitor scale must be positive")

    transform = int(monitor.get("transform", 0))
    vrr = int(bool(monitor.get("vrr", False)))

    if transform < 0 or transform > 7:
        raise ValueError("Invalid monitor transform")

    return "\n".join([
        "hl.monitor({",
        f"    output = {lua_string(name)},",
        f"    mode = {lua_string(mode)},",
        f"    position = {lua_string(f'{x}x{y}')},",
        f"    scale = {format(scale, '.10g')},",
        f"    transform = {transform},",
        f"    vrr = {vrr}",
        "})"
    ])


def generate_lua(monitors):
    blocks = [
        monitor_block(monitor)
        for monitor in sorted(
            monitors,
            key=lambda item: str(item["name"])
        )
    ]

    return (
        "-- Generated by Vesta Shell.\n"
        "-- Display settings are managed automatically.\n\n"
        + "\n\n".join(blocks)
        + "\n"
    )


def save_atomically(content):
    MONITORS_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    if MONITORS_FILE.exists() and not BACKUP_FILE.exists():
        shutil.copy2(MONITORS_FILE, BACKUP_FILE)

    original_mode = None

    if MONITORS_FILE.exists():
        original_mode = MONITORS_FILE.stat().st_mode & 0o777

    temporary_path = None

    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            prefix=".monitors-vesta-",
            suffix=".lua",
            dir=MONITORS_FILE.parent,
            delete=False
        ) as temporary:
            temporary_path = Path(temporary.name)
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())

        if original_mode is not None:
            os.chmod(temporary_path, original_mode)
        else:
            os.chmod(temporary_path, 0o644)

        os.replace(temporary_path, MONITORS_FILE)

        directory_fd = os.open(
            MONITORS_FILE.parent,
            os.O_RDONLY
        )

        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)

    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def persist():
    monitors = read_monitors()
    content = generate_lua(monitors)
    save_atomically(content)


def execute_transaction(arguments):
    process = subprocess.run(
        [sys.executable, str(TRANSACTION_SCRIPT), *arguments],
        capture_output=True,
        text=True,
        timeout=35
    )

    try:
        result = json.loads(process.stdout.strip())
    except (ValueError, TypeError):
        raise RuntimeError(
            process.stderr.strip()
            or process.stdout.strip()
            or "Invalid transaction response"
        )

    if process.returncode != 0 or result.get("ok") is not True:
        return result, 1

    return result, 0


def main():
    if len(sys.argv) < 2:
        raise ValueError("Missing action")

    action = sys.argv[1]
    result, exit_code = execute_transaction(sys.argv[1:])

    if exit_code != 0:
        print(json.dumps(result), flush=True)
        return exit_code

    if action in PERSIST_ACTIONS:
        try:
            persist()
            result["persisted"] = True
            result["configPath"] = str(MONITORS_FILE)
        except Exception as error:
            print(
                json.dumps({
                    "ok": False,
                    "error": (
                        "Display settings were applied, "
                        "but persistence failed: "
                        + str(error)
                    ),
                    "applied": True,
                    "persisted": False
                }),
                flush=True
            )
            return 1

    print(json.dumps(result), flush=True)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as error:
        print(
            json.dumps({
                "ok": False,
                "error": str(error)
            }),
            flush=True
        )
        sys.exit(1)
