#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: Ср 24 сен 2025 01:54:43 MSK

# Перенаправляем весь вывод в лог-файл
exec &> "/home/paperos/wallpaper_restore.log"

echo "--- Начинаем восстановление обоев: $(date) ---"

echo "Проверяем доступность Hyprland..."
# Ждем, пока Hyprland не будет готов принимать команды
until hyprctl -j monitors > /dev/null 2>&1; do
    echo "Hyprland недоступен, ждем 0.5с..."
    sleep 0.5
done
echo "Hyprland готов."

echo "Завершаем предыдущие процессы mpvpaper (если есть)..."
pkill -f -9 mpvpaper
echo "Готово."

echo "Получаем список мониторов..."
monitors=$(hyprctl monitors -j | jq -r '.[] | .name')
echo "Найденные мониторы: $monitors"

for monitor in $monitors; do
    echo "Устанавливаем обои для монитора: $monitor"
    mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5 load-scripts=no" "$monitor" "/home/paperos/Изображения/Wallpapers/black-hole.3840x2160.mp4" &
    sleep 0.1
done

echo "--- Скрипт завершил работу ---"
