# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Global tweaks
windowrule = opacity 0.99 override 0.99 override, match:class .*
windowrule = persistent_size on, match:class .*
windowrule = float on, match:title ^.*Console window for.*$
windowrule = float on, match:title ^.*Save file.*$
windowrule = float on, match:title ^.*Volume Control.*$
windowrule = float on, match:title ^.*— Dolphin.*$

# Uncomment to disable blur for all XWayland windows:
# windowrule = no_blur on, match:xwayland 1

# Apps — float
# windowrule = match:class ^org\.kde\.dolphin$, float on, size 1150 650
windowrule = match:class ^org\.gnome\.Calculator$, float on
windowrule = match:class ^org\.gnome\.TextEditor$, float on
windowrule = match:class ^org\.kde\.konsole$, float on
windowrule = match:class ^org\.kde\.ark$, float on
windowrule = match:class ^steam$, float on
# windowrule = match:class ^*.*$, float on
