# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in files in `custom`

# --- Environment variables ---
source=hyprland/env.conf
source=custom/env.conf

# --- Other vars ---
source=hyprland/variables.conf
source=custom/variables.conf

# --- Defaults ---
# hyprlang if !dontLoadDefaultExecs
source=hyprland/execs.conf
# hyprlang endif
# hyprlang if !dontLoadDefaultGeneral
source=hyprland/general.conf
# hyprlang endif
# hyprlang if !dontLoadDefaultRules
source=hyprland/rules.conf
# hyprlang endif
# hyprlang if !dontLoadDefaultColors
source=hyprland/colors.conf
# hyprlang endif
# hyprlang if !dontLoadDefaultKeybinds
source=hyprland/keybinds.conf
# hyprlang endif

# --- Custom ---
source=custom/execs.conf
source=custom/general.conf
source=custom/rules.conf
source=custom/keybinds.conf

# --- nwg-displays support ---
source=workspaces.conf
source=monitors.conf

# --- Shell overrides ---
source=hyprland/shellOverrides/main.conf
