# Entry point: set $HYPR_DESKTOP_SHELL to a folder under ~/.config/hypr/ (with init.conf), then reload.

# Active profile: folder name under ~/.config/hypr/ (must contain init.conf).
$HYPR_DESKTOP_SHELL = ii

# Required Global Keybind Stuff
exec = hyprctl dispatch submap global
submap = global

source = $HYPR_DESKTOP_SHELL/init.conf