$lock_cmd = qs -c ${qsConfig:-ii} ipc call lock activate || pidof hyprlock || hyprlock
# $lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = $lock_cmd
    after_sleep_cmd = qs -c ${qsConfig:-ii} ipc call lock focus
    inhibit_sleep = 3
}

listener {
    timeout = 300 # 5mins
    on-timeout = $lock_cmd
}

listener {
    timeout = 600 # 10mins
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 900 # 15mins
    on-timeout = $suspend_cmd
}
