#!/usr/bin/env bash
#
# Auto-desktopenv SSH Setup
# Automated SSH key generation and configuration
#
# Features:
#   - Generate new SSH key (ed25519)
#   - Add to ssh-agent
#   - Configure known hosts
#   - Set up SSH config
#   - Test connection
#
# Usage:
#   ssh-setup.sh [EMAIL] [--no-agent]
#
# Examples:
#   ssh-setup.sh
#   ssh-setup.sh user@example.com
#   ssh-setup.sh --no-agent
#

set -euo pipefail
source "$(dirname "$(realpath "$0")")/../../tools/lib/common.sh"





SSH_DIR="$HOME/.ssh"
SSH_KEY="$SSH_DIR/id_ed25519"
SSH_CONFIG="$SSH_DIR/config"
EMAIL="${1:-$USER@$(hostname)}"
USE_AGENT=true


# Parse args
shift_used=false
while [[ $# -gt 0 ]]; do
    if [[ "$shift_used" == "false" ]]; then
        EMAIL="$1"
        shift_used=true
    else
        case $1 in
            --no-agent) USE_AGENT=false; shift ;;
            *) echo "Unknown option: $1"; exit 1 ;;
        esac
    fi
    shift
done

if [[ $EUID -eq 0 ]]; then
    log_error "Do not run as root."
    exit 1
fi

echo ""
log_info "========================================"
log_info " SSH Setup"
log_info "========================================"
echo ""

# Create .ssh directory with proper permissions
log_info "Setting up ~/.ssh directory..."
mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"
log_success ".ssh directory ready"

# Generate SSH key if it doesn't exist
if [[ ! -f "$SSH_KEY" ]]; then
    log_info "Generating new SSH key..."
    ssh-keygen -t ed25519 -C "$EMAIL" -f "$SSH_KEY" -N ""
    log_success "SSH key generated"
else
    log_info "SSH key already exists: $SSH_KEY"
fi

# Start ssh-agent and add key
if $USE_AGENT; then
    log_info "Starting ssh-agent..."
    if ! pgrep -u "$USER" ssh-agent >/dev/null 2>&1; then
        eval "$(ssh-agent -s)" >/dev/null 2>&1
    fi

    log_info "Adding SSH key to agent..."
    ssh-add "$SSH_KEY" 2>/dev/null || log_warning "Could not add key to agent"
    log_success "SSH key added to agent"
fi

# Configure SSH config
log_info "Configuring SSH..."
cat > "$SSH_CONFIG" << 'EOF'
# Auto-generated by ssh-setup.sh

# Default settings
Host *
    AddKeysToAgent yes
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes
    ServerAliveInterval 60
    ServerAliveCountMax 3
    StrictHostKeyChecking accept-new

# GitHub
Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519

# GitLab
Host gitlab.com
    HostName gitlab.com
    User git
    IdentityFile ~/.ssh/id_ed25519

# Gitea
Host gitea
    HostName gitea.example.com
    User git
    IdentityFile ~/.ssh/id_ed25519
EOF

chmod 600 "$SSH_CONFIG"
log_success "SSH config updated"

# Display public key
echo ""
log_success "Your SSH public key:"
echo "=========================================="
cat "${SSH_KEY}.pub"
echo "=========================================="
echo ""
log_info "Add this key to GitHub/GitLab:"
echo "  GitHub:  https://github.com/settings/keys"
echo "  GitLab:  https://gitlab.com/-/user_settings/ssh_keys"
echo ""

# Test connection
log_info "Testing SSH connection to GitHub..."
if ssh -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
    log_success "GitHub SSH connection successful!"
else
    log_warning "GitHub SSH connection failed. Add your key first."
fi

echo ""
log_success "SSH setup completed"
log_info "Next steps:"
echo "  1. Add the public key to your Git provider"
echo "  2. Test: ssh -T git@github.com"
echo "  3. Clone repos using SSH URLs"
echo ""
