import QtQuick
import QtQuick.Layouts
import QtQuick.Controls
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import qs.services
import qs.modules.common
import qs.modules.common.widgets
import qs.modules.common.functions
import "./DisplayConfig" as DisplayConfig

ContentPage {
    id: displaysPage
    forceWidth: true
    interactive: (contentHeight > height) && (monitorCanvas ? !monitorCanvas.draggingCount : true)
    wheelEnabled: !(monitorCanvas && monitorCanvas.draggingCount > 0)

    property string monitorsConfPath: FileUtils.trimFileProtocol(Directories.config) + "/hypr/monitors.conf"

    function writeMonitorsConfThenReload(configStrings) {
        if (!configStrings || configStrings.length === 0) return;
        const path = monitorsConfPath;
        const esc = path.replace(/'/g, "'\"'\"'");
        const header = "# Auto-generated by End_4 — do not edit manually\n\n";
        const body = header + configStrings.map(c => "monitor = " + c).join("\n");
        const script = "mkdir -p \"$(dirname '" + esc + "')\" && cat > '" + esc + "' << 'MONITORS_EOF'\n" + body + "\nMONITORS_EOF";
        Quickshell.execDetached(["bash", "-c", script]);
        reloadTimer.start();
    }

    Timer {
        id: reloadTimer
        interval: 150
        onTriggered: Quickshell.execDetached(["hyprctl", "reload"]);
    }

    property var savedMonitorConfigs: []
    property var pendingRevertConfigs: []
    property var pendingPositions: ({})  // outputName -> {x, y}
    property var pendingModes: ({})      // outputName -> {mode, scale}
    property bool overlapBlocked: false
    /// First `monitor =` line set after Apply; skipped if refine pass would not change output
    property string _refineBaselineJoin: ""

    function parseModeString(modeStr) {
        const s = String(modeStr || "").replace(/Hz$/i, "").trim();
        const match = s.match(/^(\d+)x(\d+)@([\d.]+)$/);
        if (!match) return null;
        return { w: parseInt(match[1], 10), h: parseInt(match[2], 10), hz: parseFloat(match[3]) };
    }

    /// hyprctl monitors -j gives refreshRate with up to ~5 decimals; availableModes strings are often 2-decimal rounded.
    function formatHzFromHyprctlDouble(rr) {
        if (rr === undefined || rr === null || typeof rr !== "number" || !isFinite(rr))
            return "60";
        let s = rr.toFixed(6);
        if (s.indexOf(".") >= 0) {
            s = s.replace(/0+$/, "");
            s = s.replace(/\.$/, "");
        }
        return s;
    }

    /// Upgrade combo entries for the active WxH when catalog Hz rounds away from measured refreshRate.
    function availableModesForDisplay(m) {
        const modes = m?.availableModes || [];
        if (!m || m.refreshRate == null || typeof m.refreshRate !== "number")
            return modes;
        const rr = m.refreshRate;
        const w = m.width;
        const h = m.height;
        return modes.map(mo => {
            const p = parseModeString(String(mo).replace(/Hz$/i, ""));
            if (!p || p.w !== w || p.h !== h) return mo;
            if (Math.abs(p.hz - rr) < 0.35)
                return `${p.w}x${p.h}@${formatHzFromHyprctlDouble(rr)}Hz`;
            return mo;
        });
    }

    function indexOfDisplayMode(displayModes, selectedMode) {
        const raw = String(selectedMode || "").replace(/Hz$/i, "").trim();
        const dm = displayModes || [];
        let i = dm.findIndex(mo => String(mo).replace(/Hz$/i, "").trim() === raw);
        if (i >= 0) return i;
        const p = parseModeString(raw);
        if (!p) return 0;
        for (let j = 0; j < dm.length; j++) {
            const q = parseModeString(String(dm[j]).replace(/Hz$/i, ""));
            if (q && q.w === p.w && q.h === p.h && Math.abs(q.hz - p.hz) < 0.4) return j;
        }
        return 0;
    }

    function modeStringForCurrent(m) {
        if (!m) return "";
        const w = m.width ?? 1920;
        const h = m.height ?? 1080;
        const rr = m.refreshRate ?? 60;
        const modes = availableModesForDisplay(m);
        let best = null;
        let bestDelta = Infinity;
        for (const mode of modes) {
            const s = String(mode).replace(/Hz$/i, "").trim();
            const match = s.match(/^(\d+)x(\d+)@([\d.]+)$/);
            if (!match) continue;
            if (parseInt(match[1]) !== w || parseInt(match[2]) !== h) continue;
            const modeHz = parseFloat(match[3]);
            const delta = Math.abs(modeHz - rr);
            if (delta < bestDelta) {
                bestDelta = delta;
                best = mode;
            }
        }
        return best || (modes.find(mo => String(mo).startsWith(`${w}x${h}@`)) || modes[0]) || `${w}x${h}@${Number(rr).toFixed(3)}Hz`;
    }

    function currentModeConfig(m) {
        const s = modeStringForCurrent(m);
        return s ? String(s).replace(/Hz$/i, "").trim() : `${m.width ?? 1920}x${m.height ?? 1080}@${formatHzFromHyprctlDouble(m.refreshRate ?? 60)}`;
    }

    /// EDID-style identifier (same idea as DMS / Hyprland desc:): stable if cable names change.
    function monitorDescIdentifier(m) {
        if (!m) return "";
        if (m.description && String(m.description).length > 0)
            return "desc:" + m.description;
        const make = m.make || "";
        const model = m.model || "";
        const serial = m.serial || "Unknown";
        const parts = (make + " " + model + " " + serial).trim();
        return parts.length > 0 ? "desc:" + parts : (m.name || "");
    }

    /// Hz substring from Hyprland's mode catalog (often 2 decimals) when we cannot use refreshRate.
    function hzLiteralFromModeString(modeStr, parsed) {
        const raw = String(modeStr || "").replace(/Hz$/i, "").trim();
        const m = raw.match(/^(\d+)x(\d+)@([\d.]+)$/);
        if (m && parsed && parseInt(m[1], 10) === parsed.w && parseInt(m[2], 10) === parsed.h)
            return m[3];
        return formatHzFromHyprctlDouble(parsed?.hz ?? 60);
    }

    function resolutionStringFromMode(modeStr, m) {
        const parsed = parseModeString(modeStr);
        if (!parsed) {
            const w = m?.width ?? 1920, h = m?.height ?? 1080;
            return `${w}x${h}@${formatHzFromHyprctlDouble(m?.refreshRate ?? 60)}`;
        }
        // Hyprland JSON lists rounded Hz in availableModes but exposes precise refreshRate for the active timing.
        if (m && parsed.w === (m.width ?? 0) && parsed.h === (m.height ?? 0) && m.refreshRate != null
            && typeof m.refreshRate === "number" && isFinite(m.refreshRate)
            && Math.abs(parsed.hz - m.refreshRate) < 0.35) {
            return `${parsed.w}x${parsed.h}@${formatHzFromHyprctlDouble(m.refreshRate)}`;
        }
        const hzLit = hzLiteralFromModeString(modeStr, parsed);
        return `${parsed.w}x${parsed.h}@${hzLit}`;
    }

    function buildMonitorConfigLine(m, px, py, scale, modeStr) {
        const mode = modeStr || currentModeConfig(m);
        const resolution = resolutionStringFromMode(mode, m);
        const identifier = monitorDescIdentifier(m);
        const pos = px + "x" + py;
        let line = identifier + ", " + resolution + ", " + pos + ", " + scale;
        if (m.transform !== undefined && m.transform !== 0)
            line += ", transform, " + m.transform;
        // VRR off in generated config avoids bad interaction with rounded mode lines from hyprctl.
        line += ", vrr, 0";
        return line;
    }

    function buildLiveMonitorConfigLines() {
        const monitors = HyprlandData.monitors || [];
        return monitors.map(m => {
            const mode = currentModeConfig(m);
            const scale = Math.round((m.scale ?? 1) * 100) / 100;
            return buildMonitorConfigLine(m, m.x ?? 0, m.y ?? 0, scale, mode);
        });
    }

    function saveMonitorConfigs() {
        const monitors = HyprlandData.monitors || [];
        savedMonitorConfigs = monitors.map(m => {
            const mode = currentModeConfig(m);
            const scale = Math.round((m.scale ?? 1) * 100) / 100;
            return buildMonitorConfigLine(m, m.x ?? 0, m.y ?? 0, scale, mode);
        });
    }

    function getLogicalRect(m, pos) {
        const x = pos ? pos.x : (m.x ?? 0);
        const y = pos ? pos.y : (m.y ?? 0);
        const s = m.scale ?? 1;
        const w = Math.round((m.width ?? 1920) / s);
        const h = Math.round((m.height ?? 1080) / s);
        return { x, y, w, h };
    }

    function rectsOverlap(a, b) {
        return a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y;
    }

    function buildConfigsToApply() {
        const monitors = HyprlandData.monitors || [];
        const configs = monitors.map(m => {
            const pos = pendingPositions[m.name];
            const px = pos ? pos.x : (m.x ?? 0);
            const py = pos ? pos.y : (m.y ?? 0);
            const pm = pendingModes[m.name];
            const mode = pm ? pm.mode : currentModeConfig(m);
            let scale = pm ? pm.scale : (m.scale ?? 1);
            scale = Math.max(0.5, Math.min(3, Number(scale)));
            scale = Math.round(scale * 100) / 100;
            return { name: m.name, mode, px, py, scale, m };
        });
        const rects = configs.map(c => getLogicalRect(c.m, { x: c.px, y: c.py }));
        for (let i = 0; i < rects.length; i++)
            for (let j = i + 1; j < rects.length; j++)
                if (rectsOverlap(rects[i], rects[j]))
                    return null;
        return configs.map(c => buildMonitorConfigLine(c.m, c.px, c.py, c.scale, c.mode));
    }

    function applyAll() {
        const configs = buildConfigsToApply();
        if (!configs) {
            overlapBlocked = true;
            return;
        }
        overlapBlocked = false;
        saveMonitorConfigs();
        const revertConfigs = [...savedMonitorConfigs];
        _refineBaselineJoin = configs.join("\n");
        refineMonitorConfTimer.stop();
        writeMonitorsConfThenReload(configs);
        displayConfirm.revertCallback = () => {
            writeMonitorsConfThenReload(revertConfigs);
        };
        pendingPositions = {};
        pendingModes = {};
        displayConfirm.open();
        applyConfirmTimer.start();
    }

    function hasPendingChanges() {
        return Object.keys(pendingPositions).length > 0 || Object.keys(pendingModes).length > 0;
    }

    readonly property int snapThreshold: 80
    function snapToEdges(outputName, x, y) {
        const monitors = HyprlandData.monitors || [];
        const self = monitors.find(m => m.name === outputName);
        if (!self) return { x, y };
        const s = self.scale ?? 1;
        const w = Math.round((self.width ?? 1920) / s);
        const h = Math.round((self.height ?? 1080) / s);
        let outX = x, outY = y;
        for (const m of monitors) {
            if (m.name === outputName) continue;
            const pos = pendingPositions[m.name];
            const mx = pos ? pos.x : (m.x ?? 0);
            const my = pos ? pos.y : (m.y ?? 0);
            const mw = Math.round((m.width ?? 1920) / (m.scale ?? 1));
            const mh = Math.round((m.height ?? 1080) / (m.scale ?? 1));
            if (Math.abs(outX - (mx + mw)) <= snapThreshold && outY + h > my && outY < my + mh)
                outX = mx + mw;
            if (Math.abs(outX + w - mx) <= snapThreshold && outY + h > my && outY < my + mh)
                outX = mx - w;
            if (Math.abs(outY - (my + mh)) <= snapThreshold && outX + w > mx && outX < mx + mw)
                outY = my + mh;
            if (Math.abs(outY + h - my) <= snapThreshold && outX + w > mx && outX < mx + mw)
                outY = my - h;
        }
        return { x: outX, y: outY };
    }

    function displayLabel(m) {
        if (!m) return Translation.tr("Display");
        return m.description || m.model || m.make || m.manufacturer || m.name || Translation.tr("Display");
    }

    property var popupOverlay: null
    function setPopupOverlay(overlay) { popupOverlay = overlay; }

    DisplayConfig.DisplayConfirmPopup {
        id: displayConfirm
        parent: displaysPage.popupOverlay || displaysPage
        onConfirmed: {
            Hyprland.refreshMonitors();
            Hyprland.refreshWorkspaces();
        }
    }

    Timer {
        id: applyConfirmTimer
        interval: 350
        onTriggered: {
            Hyprland.refreshMonitors();
            Hyprland.refreshWorkspaces();
            HyprlandData.updateMonitors();
            Qt.callLater(() => {
                Hyprland.refreshMonitors();
                Hyprland.refreshWorkspaces();
            });
            applyConfirmRetryTimer.start();
        }
    }
    Timer {
        id: applyConfirmRetryTimer
        interval: 700
        repeat: false
        onTriggered: {
            Hyprland.refreshMonitors();
            Hyprland.refreshWorkspaces();
            HyprlandData.updateMonitors();
            refineMonitorConfTimer.restart();
        }
    }

    Timer {
        id: refineMonitorConfTimer
        interval: 450
        repeat: false
        onTriggered: {
            const lines = displaysPage.buildLiveMonitorConfigLines();
            if (lines.length === 0) return;
            const j = lines.join("\n");
            if (j === displaysPage._refineBaselineJoin) return;
            displaysPage.writeMonitorsConfThenReload(lines);
        }
    }

    ContentSection {
        icon: "monitor"
        title: Translation.tr("Monitor configuration")

        ContentSubsection {
            title: Translation.tr("Arrange displays")
            tooltip: Translation.tr("Drag monitors to reposition. Apply below to save changes.")

            DisplayConfig.MonitorCanvas {
                id: monitorCanvas
                Layout.fillWidth: true
                pendingPositions: displaysPage.pendingPositions
                onMonitorPositionChanged: (name, x, y) => {
                    displaysPage.overlapBlocked = false;
                    const snapped = displaysPage.snapToEdges(name, x, y);
                    const next = {};
                    for (const k of Object.keys(displaysPage.pendingPositions))
                        next[k] = displaysPage.pendingPositions[k];
                    next[name] = { x: snapped.x, y: snapped.y };
                    displaysPage.pendingPositions = next;
                }
            }

            RowLayout {
                Layout.fillWidth: true
                Layout.topMargin: 12
                spacing: 12
                Item { Layout.fillWidth: true }
                StyledText {
                    visible: displaysPage.overlapBlocked
                    text: Translation.tr("Monitors overlap — drag them apart to apply")
                    font.pixelSize: Appearance.font.pixelSize.small
                    color: "orange"
                    Layout.alignment: Qt.AlignVCenter
                }
                StyledText {
                    visible: displaysPage.hasPendingChanges() && !displaysPage.overlapBlocked
                    text: Translation.tr("Unsaved display changes")
                    font.pixelSize: Appearance.font.pixelSize.small
                    color: Appearance.colors.colSubtext
                    Layout.alignment: Qt.AlignVCenter
                }
                RippleButtonWithIcon {
                    materialIcon: "check"
                    mainText: Translation.tr("Apply")
                    visible: displaysPage.hasPendingChanges()
                    onClicked: displaysPage.applyAll()
                }
            }
        }

        ContentSubsection {
            ColumnLayout {
                Layout.fillWidth: true
                spacing: 12

                Repeater {
                    model: HyprlandData.monitors

                    delegate: ColumnLayout {
                        id: monitorDelegate
                        required property var modelData
                        Layout.fillWidth: true
                        spacing: 14

                        property string selectedMode: ""
                        Component.onCompleted: {
                            const pm = displaysPage.pendingModes[modelData.name];
                            const dmodes = displaysPage.availableModesForDisplay(modelData);
                            if (pm) {
                                const m = dmodes.find(mo => String(mo).replace(/Hz$/i, "") === pm.mode)
                                    || displaysPage.availableModesForDisplay(modelData).find(mo => {
                                        const a = displaysPage.parseModeString(String(mo).replace(/Hz$/i, ""));
                                        const b = displaysPage.parseModeString(pm.mode);
                                        return a && b && a.w === b.w && a.h === b.h && Math.abs(a.hz - b.hz) < 0.4;
                                    }) || dmodes[0];
                                selectedMode = m || displaysPage.modeStringForCurrent(modelData);
                                let s = pm.scale;
                                if (typeof s === "number" && s > 10) s = s / 100;
                                monitorScale = Math.max(0.5, Math.min(3, s ?? 1));
                            } else {
                                selectedMode = displaysPage.modeStringForCurrent(modelData);
                            }
                        }
                        property real monitorScale: modelData.scale ?? 1.0
                        property bool scaleInitialized: false

                        function storePendingMode() {
                            displaysPage.overlapBlocked = false;
                            const modeStr = (selectedMode || "").replace(/Hz$/i, "");
                            const curMode = currentModeConfig(modelData);
                            const curScale = modelData.scale ?? 1;
                            const next = {};
                            for (const k of Object.keys(displaysPage.pendingModes))
                                if (k !== modelData.name) next[k] = displaysPage.pendingModes[k];
                            if (modeStr !== curMode || monitorScale !== curScale)
                                next[modelData.name] = { mode: modeStr, scale: monitorScale };
                            displaysPage.pendingModes = next;
                        }

                        RowLayout {
                            Layout.fillWidth: true
                            spacing: 10
                            MaterialSymbol {
                                iconSize: 22
                                text: "monitor"
                                color: Appearance.colors.colPrimary
                            }
                            StyledText {
                                text: displaysPage.displayLabel(modelData)
                                font.pixelSize: Appearance.font.pixelSize.larger
                                font.weight: Font.Medium
                                color: Appearance.colors.colOnSecondaryContainer
                            }
                        }

                        RowLayout {
                            Layout.fillWidth: true
                            spacing: 16
                            StyledComboBox {
                                Layout.fillWidth: true
                                Layout.minimumWidth: 180
                                readonly property var dmodes: displaysPage.availableModesForDisplay(modelData)
                                model: dmodes
                                currentIndex: displaysPage.indexOfDisplayMode(dmodes, selectedMode)
                                onActivated: index => {
                                    if (index >= 0 && index < dmodes.length) selectedMode = dmodes[index];
                                    monitorDelegate.storePendingMode();
                                }
                            }
                            ConfigSpinBox {
                                id: scaleSpinBox
                                text: Translation.tr("Scale")
                                Layout.preferredWidth: 140
                                Layout.minimumWidth: 120
                                from: 50
                                to: 300
                                stepSize: 25
                                Component.onCompleted: {
                                    const v = Math.round(monitorScale * 100);
                                    if (v >= 50 && v <= 300) value = v;
                                    Qt.callLater(() => scaleInitialized = true);
                                }
                                onValueChanged: {
                                    if (!scaleInitialized) return;
                                    const newScale = Math.max(0.5, Math.min(3, value / 100));
                                    if (Math.abs(newScale - monitorScale) > 0.005) {
                                        monitorScale = newScale;
                                        storePendingMode();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        ContentSubsection {
            title: Translation.tr("Brightness")
            Layout.topMargin: 16

            ColumnLayout {
                Layout.fillWidth: true
                spacing: 14

                Repeater {
                    model: Brightness.monitors
                    delegate: RowLayout {
                            required property var modelData
                            Layout.fillWidth: true
                            spacing: 12
                            visible: modelData.ready
                            MaterialSymbol {
                                iconSize: 22
                                text: "brightness_6"
                                color: Appearance.colors.colPrimary
                            }
                            StyledText {
                                text: modelData.screen ? displaysPage.displayLabel(modelData.screen) : Translation.tr("Display")
                                font.pixelSize: Appearance.font.pixelSize.small
                                font.weight: Font.Medium
                                color: Appearance.colors.colOnSecondaryContainer
                                Layout.preferredWidth: 90
                            }
                            StyledSlider {
                                from: 0
                                to: 1
                                value: modelData.brightness
                                configuration: StyledSlider.Configuration.XS
                                usePercentTooltip: true
                                Layout.fillWidth: true
                                onMoved: modelData.setBrightness(value)
                                Connections {
                                    target: modelData
                                    function onBrightnessChanged() { modelData.brightness }
                                }
                            }
                        }
                    }
                    StyledText {
                        visible: Brightness.monitors.length === 0
                        text: Translation.tr("No brightness-capable displays detected")
                        font.pixelSize: Appearance.font.pixelSize.small
                        color: Appearance.colors.colSubtext
                    }
                }
            }
        }

    ContentSection {
        icon: "nightlight"
        title: Translation.tr("Night light")

        ContentSubsection {
            title: Translation.tr("Schedule & temperature")
            tooltip: Translation.tr("Adjust night light schedule and color temperature.")

            ColumnLayout {
                Layout.fillWidth: true
                spacing: 16

                ConfigSwitch {
                    buttonIcon: "bedtime"
                    text: Translation.tr("Automatic schedule")
                    checked: Config.options.light.night.automatic
                    onCheckedChanged: Config.options.light.night.automatic = checked
                }
                RowLayout {
                    enabled: Config.options.light.night.automatic
                    spacing: 8
                    MaterialTextArea {
                        Layout.preferredWidth: 72
                        placeholderText: "19:00"
                        text: Config.options.light.night.from
                        wrapMode: TextEdit.NoWrap
                        onTextChanged: Config.options.light.night.from = text
                    }
                    StyledText { text: "–"; color: Appearance.colors.colSubtext; Layout.alignment: Qt.AlignVCenter }
                    MaterialTextArea {
                        Layout.preferredWidth: 72
                        placeholderText: "06:30"
                        text: Config.options.light.night.to
                        wrapMode: TextEdit.NoWrap
                        onTextChanged: Config.options.light.night.to = text
                    }
                    StyledText {
                        text: Translation.tr("(24h)")
                        font.pixelSize: Appearance.font.pixelSize.smaller
                        color: Appearance.colors.colSubtext
                        Layout.alignment: Qt.AlignVCenter
                    }
                }
                ConfigSpinBox {
                    icon: "thermostat"
                    text: Translation.tr("Color temperature (K)")
                    value: Config.options.light.night.colorTemperature
                    from: 2700
                    to: 6500
                    stepSize: 100
                    onValueChanged: Config.options.light.night.colorTemperature = value
                }
            }
        }
    }
}
