background            #$term0 #

color0                #$term0 #
color1                #$term1 #
color2                #$term2 #
color3                #$term3 #
color4                #$term4 #
color5                #$term5 #
color6                #$term6 #
color7                #$term7 #
color8                #$term8 #
color9                #$term9 #
color10               #$term10 #
color11               #$term11 #
color12               #$term12 #
color13               #$term13 #
color14               #$term14 #
color15               #$term15 #

cursor                #$term7 #

foreground            #$term7 #

selection_background  #$onSecondaryContainer #
selection_foreground  #$secondaryContainer #

# Override obscure colors for starship prompt (these are greys at the end)
color255              #$primary #
color254              #$primaryContainer #
color253              #$secondary #
color252              #$secondaryContainer #
color251              #$tertiary #
color250              #$tertiaryContainer #
color249              #$error #
color248              #$errorContainer #

color232              #$onPrimary #
color233              #$onPrimaryContainer #
color234              #$onSecondary #
color235              #$onSecondaryContainer #
color236              #$onTertiary #
color237              #$onTertiaryContainer #
color238              #$onError #
color239              #$onErrorContainer #
color240              #$onPrimary # // Somehow 232 doesn't work so i gotta use another number

# Some stuff should specifically use the colors in the middle so they look acceptable in both unthemed light/dark
color243              #$primary #
color244              #$error #
color245              #$outlineVariant #
